version: "3.8"

services: 
    db:
        image: mongo
        restart: always
        volumes: 
            - data:/data/db
        env_file: 
            - ./env/mongo.env
        ports:
            - "27017:27017"
    
volumes: 
    data:



